language: node_js

node_js:
  - '8'
  - '10'
  - '12'

cache: npm

install:
  - npm i

script:
  - npm test
  - npm run dev unko
  - npm run dev unko | npm run dev -- -d

deploy:
  provider: npm
  email: amanoese@gmail.com
  on:
    tags: true
  api_key: $NPM_TOKEN
